!classDefinition: #Pepe category: #'Ejercicio 1'!
DenotativeObject subclass: #Pepe
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio 1'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Pepe class' category: #'Ejercicio 1'!
Pepe class
	instanceVariableNames: ''!

!Pepe class methodsFor: '-- all --' stamp: 'JD 8/14/2024 12:53:36'!
hola
	^'chau'! !
